### ISSUE TITLE
 0.00ns=  0.00c latency for VZEROALL

### ISSUE THREAD

**Issue by maximmasiutin** [InstLatx64/InstLatx64#1]
Tables fror Skylake, Kaby Lake show  0.00ns=  0.00c latency for the VZEROALL instructions:
http://users.atw.hu/instlatx64/GenuineIntel00506E3_Skylake2_InstLatX64.txt
1913 AVX             :VZEROALL                              L: [no true dep.]   T:   0.00ns=  0.00c

This is the only instruction that shows zero latency in the table.

What is the real latency of VZEROALL? Is it actually faster or slower than VZEROUPPER?

**Comment by InstLatx64** [comment]
Thank you for the riport!
This is a bug, VZEROALL throughput is never 0.
The VZEROUPPER seems always faster with the few retested x64 config:
                                          VZEROUPPER    VZEROALL
CPUID AMD 600F12  (BDZ)        5                     10
CPUID AMD 800F11  (Ryzen)     6                      11
CPUID Intel   306E4 (IVB)           1                       9
CPUID Intel   306C3 (HSW)        1                       8
CPUID Intel   506E3 (SKL)           1                      12

**Comment by maximmasiutin** [comment]
By the way, according to Intel documentation https://www.intel.com/content/dam/doc/manual/64-ia-32-architectures-optimization-manual.pdf - see, for example, part 2.1.3.1 (Renamer):

>Some micro-ops can execute to completion during rename and are removed from the pipeline at that point, effectively costing no execution bandwidth. These include:
>• Zero idioms (dependency breaking idioms)
>• NOP
>• VZEROUPPER
>• FXCHG

Also, section 11.3 tells the following:

> To enable fast transition between 256-bit Intel AVX and Intel SSE code, use the VZEROUPPER instruction. The VZEROUPPER instruction resets the upper 128 bits of all Intel AVX registers. This instruction has zero latency.

Table C-3. 256-bit AVX Instructions (Contd.) also explicitly lists VZEROUPPER as a zero-latency instruction.

The document doesn't tell anything about VZEROALL, but I suspect that it also has Zero latency.

So, this is probably not a bug, but a special case, which we should handle differently.

**Comment by maximmasiutin** [comment]
New version of AIDA will have that fixed.

**Comment by InstLatx64** [comment]
7 dump (IVB-E, HSW, BDW-U, SKL, SKX, BDZ, Ryzen) refreshed with VZEROALL fixed dumps
