### ISSUE TITLE
Quark URL gives 404

### ISSUE THREAD

**Issue by Torinde** [InstLatx64/InstLatx64#10]
Currently there is only one URL for Intel Quark:
![image](https://github.com/InstLatx64/InstLatx64/assets/97228894/fda695fb-d04d-411b-82b4-2ebe06eb2e70)

[CPUID Dump](http://users.atw.hu/instlatx64/GenuineIntel/GenuineIntel0000590_Lakemont_CPUID2.txt)

It goes to 404 page.

Maybe it has to go to [GenuineIntel0000590_Clanton_CPUID2.txt](http://users.atw.hu/instlatx64/GenuineIntel/GenuineIntel0000590_Clanton_CPUID2.txt) (this one works) or another page instead?
- ECX value seems strange (if I'm decoding it correctly) - claiming support for SSSE3 and AVX??

**Comment by InstLatx64** [comment]
Thx, I have uploaded a [fixed dump](https://github.com/InstLatx64/InstLatx64/blob/master/GenuineIntel/GenuineIntel0000590_Lakemont_03_CPUID.txt).
The old one was from Intel SDE 7.80, and was swapped the CPUID.1.EBX and CPUID.1.ECX. 
I have rebuilt it from [Quark Developer Manual](https://www.intel.com/content/dam/support/us/en/documents/processors/quark/sb/intelquarkcore_devman_001.pdf).

**Comment by InstLatx64** [comment]
Thx, Intel Quark X1000 filename is now [GenuineIntel0000590_Clanton_03_CPUID.txt](https://github.com/InstLatx64/InstLatx64/blob/master/GenuineIntel/GenuineIntel0000590_Clanton_03_CPUID.txt)

**Comment by tremalrik** [comment]
For the Quark D2000 ("Mint Valley", signature 0x596), it appears to be possible to reconstruct a full CPUID dump from public Intel documentation ( https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/quark-d2000-datasheet.pdf , order no. 335577-005EN, section 11.5, page 108) in the same way as for the X1000.

For the other Quarks:
* I've been unable to find similarly detailed information for Quark SE C1000 ("Atlas Peak"). It is documented to support the CPUID instruction ( http://www.intel.com/content/dam/www/public/us/en/documents/datasheets/quark-c1000-datasheet.pdf , order no. 334712-005EN, section 13.1, page 129 ), but the documentation does not provide the actual CPUID data the way the D2000 documentation does. The Quark SE C1000 appears to have had at least two steppings "A0" and "A1" ( https://web.archive.org/web/20161022202218/http://ark.intel.com/products/91949/Intel-Quark-SE-C1000-Microcontroller#@ordering ), but the CPUID signatures for these two steppings seem nowhere to be found. (The Quark SE 1000 is used in some Arduino 101 boards, but it appears to be difficult to actually run CPUID or any other user-provided x86 code on these boards   - the SE C1000 also features an ARC RISC CPU core in addition to the x86 core, and the Arduino "sketches" which can be easily uploaded to the device will run on the ARC core, not the x86 core)
* The D1000 ("Silver Butte") implements a heavily cut-down version of the i386 instruction set, with no CPUID nor even a signature in the EDX reset-value ( Quark D1000 programmer's reference manual, https://cdrdv2.intel.com/v1/dl/getContent/332913 , order no. 332913-002US, see pages 14 and 42 )
* There is also a Quark S1000 ("Sue Creek"), which, despite using the Quark brand name, is not x86 at all ( https://www.cnx-software.com/2017/06/19/intel-quark-s1000-sue-creek-processor-to-support-on-chip-speech-recognition/ )

**Comment by InstLatx64** [comment]
Thank you very much!
[Intel Quark D2000 (Mint Valley) CPUID dump](https://github.com/InstLatx64/InstLatx64/blob/master/GenuineIntel/GenuineIntel0000596_MintValley_01_CPUID.txt)
