### ISSUE TITLE
Rise Lynx - Kirin name swap?

### ISSUE THREAD

**Issue by Torinde** [InstLatx64/InstLatx64#11]
![image](https://github.com/InstLatx64/InstLatx64/assets/97228894/ebdca7e5-bb5e-40eb-b9db-4b4ce7ba364a)

[BIOS Writer's Guide: iDRAGON mP6 MICROPROCESSOR](https://www.mail-archive.com/tech@openbsd.org/msg70441.html):
family 5 model 0      RiSE iDragon (0.25 um)	[Lynx](https://datasheets.chipdb.org/Rise/mP6_iDragon/Lynx_WEB1.pdf)
family 5 model 2      RiSE iDragon (0.18 um)	[Kirin](https://datasheets.chipdb.org/Rise/mP6_iDragon/kirin_ds.pdf)

It seems the Lynx/Kirin codenames for 0.25/0.18 are swapped?

**Comment by InstLatx64** [comment]
250 nm = Kirin, 180 nm = Lynx is according to 
1, [Linux source](https://lwn.net/Articles/486162/)
2, [CPU-collection](https://www.cpu-collection.de/?tn=0&l0=co&l1=Rise&l2=mP6#mP6)
3, [CPU museum](https://cpumuseum.jimdofree.com/museum/rise-technology/mp6/)
It seems chipdb is just using wrong filenames in this case.
