### ISSUE TITLE
Vortex86MX shows no MMX

### ISSUE THREAD

**Issue by Torinde** [InstLatx64/InstLatx64#12]
Vortex86MX dump seems to lack MMX?
![image](https://github.com/InstLatx64/InstLatx64/assets/97228894/02103ea7-704b-4e78-81dc-d4c0d3f843ab)

While it actually [supports MMX](https://www.flickr.com/photos/46578721@N08/4296160520/) (What does "CPU is slow. Windows runs optimally on **G5 class** or better..." refer to?)

RDC IAD dump shows MMX? (and it uses similar/related CPU with Vortex86MX, both have the same FamilyModelStepping)
![image](https://github.com/InstLatx64/InstLatx64/assets/97228894/f38095c6-70ed-4e59-8f3d-c647e776ec34)

**Comment by InstLatx64** [comment]
Thx, I have uploaded a reconstructed [MMX enabled dump](https://github.com/InstLatx64/InstLatx64/blob/master/Vortex86_SoC/Vortex86%20SoC0000586_Vortex86MX_MMX_CPUID.txt).
